### ISSUE TITLE
Klageskjema eksisterer ikke

### ISSUE THREAD

**Issue by kienvu-nav** [navikt/klage-dittnav#264]
Vi i team lønnskompensasjon har fått henvendelse om at klage løsning ikke fungerer i prod. Tittet litt i koden og fant ut at denne url'n ikke fungerer.

https://github.com/navikt/klage-dittnav/blob/b2963b2427ac001ec9c9a26e3954c8002d29b3ed/src/kategorier/kategorier.ts#L36

**Comment by cskrov** [comment]
Stemmer, vi oppdaget dette nylig, men har ikke funnet den korrekte lenken.
Har funnet frem til https://www.nav.no/soknader/nb/person/korona/permittering.

Har du mulighet til å sende oss korrekt lenke?

**Comment by cskrov** [comment]
Fikset i PR #265.
